language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master
    - 4.0.x
    - 4.1.x
    - 4.2.x
    - 4.3.x

install: 'gem install bundler -v ">= 1.7.12" && bundle install --retry=10'

env:
  - ON_TRAVIS_CI=yes

sudo: false
